apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: locust
resources:
  - namespace.yaml
  - locust-master-deployment.yaml
  - locust-master-service.yaml
  - locust-worker-deployment.yaml
  - ingress2.yaml
configMapGenerator:
  - name: locust
